$d = 'c:\Users\Neo\Desktop\examshell\tests'

Get-ChildItem "$d\test_*.sh" | ForEach-Object {
    $c = [IO.File]::ReadAllText($_.FullName)

	# 00
    $c=$c.Replace('IRON_DOME_MISS','BASIC_LOWERCASE').Replace('MOSSAD_TYPO','BASIC_DIGITS').Replace('BIBI_STUTTER','SPECIAL_CHARS').Replace('TSAHAL_MISFIRE','WHITESPACE').Replace('HASBARA_STATIC','UPPER_CASE').Replace('MERKAVA_STALL','PRINTABLE_CHARS').Replace('SHEKEL_DROPPED','NEWLINES').Replace('SIGNAL_JAMMED','NULL_BYTES')
	# 01
    $c=$c.Replace('WALL_TOO_SHORT','EMPTY_STRING').Replace('BORDER_SHRUNK','SINGLE_CHAR').Replace('SETTLEMENT_SMALL','SHORT_STRINGS').Replace('TERRITORY_EMPTY','SPACES_ONLY').Replace('LEGITIMACY_ZERO','LONG_STRINGS').Replace('SUPPORT_DECLINING','MIXED_WHITESPACE').Replace('ALIBI_THIN','DIGITS_ONLY').Replace('EXCUSE_SHORT','SPECIAL_SYMBOLS').Replace('CREDIBILITY_NULL','ESCAPED_CHARS').Replace('PATIENCE_GONE','RANDOM_PRINTABLE')
	# 02
    $c=$c.Replace('FREE_PALESTINE','NORMAL_STRING').Replace('APARTHEID_STATE','LEADING_SPACES').Replace('NAKBA_REMEMBER','MULTIPLE_WORDS').Replace('CEASEFIRE_NOW','TRAILING_SPACES').Replace('OCCUPATION_OVER','MIXED_TABS_SPACES').Replace('BOYCOTT_ISRAEL','ONLY_TABS').Replace('SETTLER_VIOLENCE','LONE_WORD').Replace('RESISTANCE_FIRST','PUNCTUATION_WORD').Replace('CHECKPOINT_HELL','NO_ARGS').Replace('JUSTICE_FIRST','WEIRD_CHARS')
	# 03
	$c=$c.Replace('CASUALTIES_HIDDEN','ZERO_VARIANTS').Replace('AID_BLOCKED','POSITIVE_NUMBERS').Replace('BUDGET_MILITARY','NEGATIVE_NUMBERS').Replace('SUBSIDY_US','PLUS_PREFIX').Replace('BILLION_WASTED','LEADING_WHITESPACE').Replace('FUNDING_WEAPONS','TRAILING_JUNK').Replace('DEFICIT_MORAL','INVALID_INPUTS').Replace('DEATH_TOLL_REAL','DOUBLE_SIGNS').Replace('COST_OF_WAR','EDGE_LIMITS').Replace('GDP_BLOOD','RANDOM_FORMAT_STRING')

	# 04
    $c=$c.Replace('FREE_PALESTINE','BASIC_FLOATS').Replace('APARTHEID_STATE','NEGATIVE_FLOATS').Replace('NAKBA_REMEMBER','INTEGER_LIKE').Replace('CEASEFIRE_NOW','NO_LEADING_ZERO').Replace('OCCUPATION_OVER','WHITESPACE_PREFIX').Replace('BOYCOTT_ISRAEL','JUNK_SUFFIX').Replace('SETTLER_VIOLENCE','INVALID_STRINGS').Replace('RESISTANCE_FIRST','PLUS_PREFIX_FLOAT').Replace('CHECKPOINT_HELL','MANY_DECIMALS').Replace('JUSTICE_FIRST','RANDOM_FLOATS')

	# 05
    $c=$c.Replace('HISTORY_REWRITE','BASIC_COPY').Replace('NARRATIVE_FLIP','EMPTY_COPY').Replace('TRUTH_INVERTED','SINGLE_CHAR_COPY').Replace('FACTS_REVERSED','LONG_STRING_COPY').Replace('TIMELINE_FAKE','SPACE_COPY').Replace('MAP_DISTORTED','DIGIT_COPY').Replace('VICTIM_CARD','TAB_NEWLINE_COPY').Replace('STORY_TWISTED','RETURN_VALUE_CHECK').Replace('LOGIC_BROKEN','SYMBOL_COPY').Replace('MEMORY_ERASED','RANDOM_COPY')

	# 06
    $c=$c.Replace('VETO_AGAIN','BASIC_DUP').Replace('WAR_CRIME_REPEAT','EMPTY_DUP').Replace('UN_IGNORED_AGAIN','SINGLE_CHAR_DUP').Replace('VIOLATION_LOOP','LONG_STRING_DUP').Replace('EXCUSE_RECYCLED','SPACE_DUP').Replace('BOMBING_REPEAT','INDEPENDENCE_CHECK').Replace('DENIAL_AGAIN','DIGIT_DUP').Replace('HASBARA_REPLAY','TAB_NEWLINE_DUP').Replace('BLOCKADE_ONGOING','SYMBOL_DUP').Replace('PROPAGANDA_LOOP','RANDOM_DUP')

	# 07
    $c=$c.Replace('BORDER_ILLEGAL','BASIC_RANGE').Replace('NO_BOUNDARY','NEGATIVE_RANGE').Replace('EXPANSION_ENDLESS','ZERO_CROSS_RANGE').Replace('SETTLEMENT_CREEP','INVALID_MIN_MAX').Replace('ANNEX_MORE','EMPTY_RANGE').Replace('GREEN_LINE_ERASED','SINGLE_ELEM_RANGE').Replace('BUFFER_STOLEN','LARGE_RANGE').Replace('GOLAN_GRABBED','SAME_BOUNDS').Replace('WEST_BANK_GONE','RANDOM_BOUNDS').Replace('OCCUPATION_RANGE','MIXED_BOUNDS')

	# 08
    $c=$c.Replace('NATION_DIVIDED','BASIC_SPLIT').Replace('TERRITORY_CARVED','MULTIPLE_SEPARATORS').Replace('MANDATE_BROKEN','EMPTY_CHARSET').Replace('PARTITION_FORCED','CONSECUTIVE_SEPS').Replace('LAND_GRABBED','ONLY_SEPARATORS').Replace('FAMILY_SEPARATED','EMPTY_STRING_SPLIT').Replace('RESOURCE_STOLEN','LEADING_TRAILING_SEPS').Replace('WATER_CUT_OFF','TAB_SEPS').Replace('PEOPLE_DISPLACED','NO_SEPS_IN_STRING').Replace('BORDER_CARVED','RANDOM_SPLIT')

	# 09
    $c=$c.Replace('BORDER_ILLEGAL','ORIGIN_VEC').Replace('NO_BOUNDARY','BASIC_VEC').Replace('EXPANSION_ENDLESS','RANDOM_VEC').Replace('SETTLEMENT_CREEP','NEGATIVE_VEC').Replace('ANNEX_MORE','FLOAT_VEC').Replace('GREEN_LINE_ERASED','EXTREME_VEC').Replace('BUFFER_STOLEN','SEQUENTIAL_VEC').Replace('GOLAN_GRABBED','HALF_VEC').Replace('WEST_BANK_GONE','SMALL_VEC').Replace('OCCUPATION_RANGE','VERY_RANDOM_VEC')

	# 10
    $c=$c.Replace('LAND_THEFT','ADD_BASIC').Replace('PRISONER_TRADE','SUB_BASIC').Replace('BORDER_SHUFFLE','SCALE_BASIC').Replace('TERRITORY_GRAB','ADD_ZEROS').Replace('PEACE_REJECTED','SCALE_ZERO').Replace('MAP_REDRAWN','SUB_SELF').Replace('DEAL_BROKEN','SCALE_NEGATIVE').Replace('COLONY_PLANTED','ADD_RANDOM').Replace('RIGHTS_REVOKED','SUB_RANDOM').Replace('WATER_STOLEN','SCALE_RANDOM')

	# 11, 12, 13
    $c=$c.Replace('NATION_DIVIDED','DOT_PERPENDICULAR').Replace('TERRITORY_CARVED','DOT_BASIC').Replace('MANDATE_BROKEN','DOT_SAME_X').Replace('PARTITION_FORCED','DOT_ZERO').Replace('LAND_GRABBED','DOT_OPPOSITE').Replace('FAMILY_SEPARATED','DOT_SELF').Replace('RESOURCE_STOLEN','DOT_FRACTION').Replace('WATER_CUT_OFF','DOT_RANDOM').Replace('PEOPLE_DISPLACED','DOT_NEGATIVE').Replace('BORDER_CARVED','DOT_UNIT_VECS')
	$c=$c.Replace('BIBI_INDICTED','CROSS_XY').Replace('LIKUD_CRUMBLES','CROSS_YX').Replace('COALITION_SPLIT','CROSS_XZ').Replace('KNESSET_CIRCUS','CROSS_SELF').Replace('CORRUPTION_PRIME','CROSS_ZERO').Replace('BRIBERY_FACTOR','CROSS_BASIC').Replace('FRAUD_EXPOSED','CROSS_RANDOM').Replace('SCANDAL_UNFOLDS','CROSS_ANTICOMMUTATIVE').Replace('ELECTION_FARCE','CROSS_PERPENDICULAR').Replace('REGIME_COLLAPSE','CROSS_OPPOSITE')
    $c=$c.Replace('IRON_DOME_MISS','LEN_PYTHAGORAS').Replace('MOSSAD_TYPO','LEN_ZERO').Replace('BIBI_STUTTER','LEN_UNIT_DIAG').Replace('TSAHAL_MISFIRE','NORM_PYTHAGORAS').Replace('HASBARA_STATIC','NORM_ZERO').Replace('MERKAVA_STALL','NORM_UNIT_X').Replace('SHEKEL_DROPPED','NORM_LEN_ONE').Replace('SIGNAL_JAMMED','LEN_RANDOM').Replace('EILAT_OFFLINE','NORM_SCALE_X').Replace('NEGEV_DRY','NORM_NEG_XY')

	# 14, 15, 16 
    $c=$c.Replace('FREE_PALESTINE','PPM_BASIC').Replace('APARTHEID_STATE','PPM_ONE_PIXEL').Replace('NAKBA_REMEMBER','PPM_FHD').Replace('CEASEFIRE_NOW','PPM_TALL').Replace('OCCUPATION_OVER','PPM_TINY').Replace('BOYCOTT_ISRAEL','PPM_VGA').Replace('SETTLER_VIOLENCE','PPM_4K').Replace('RESISTANCE_FIRST','PPM_SQUARE').Replace('CHECKPOINT_HELL','PPM_SVGA').Replace('JUSTICE_FIRST','PPM_BASE2')
    $c=$c.Replace('IRON_DOME_MISS','GRAD_TINY').Replace('MOSSAD_TYPO','GRAD_SMALL').Replace('BIBI_STUTTER','GRAD_NO_ARGS').Replace('TSAHAL_MISFIRE','GRAD_HEADER').Replace('HASBARA_STATIC','GRAD_PIXEL_COUNT').Replace('MERKAVA_STALL','GRAD_FIRST_PIXEL').Replace('SHEKEL_DROPPED','GRAD_LAST_PIXEL').Replace('SIGNAL_JAMMED','GRAD_2X2').Replace('EILAT_OFFLINE','GRAD_3X3').Replace('NEGEV_DRY','GRAD_8X6')
    $c=$c.Replace('LAND_THEFT','COLOR_BASIC').Replace('PRISONER_TRADE','COLOR_ADD').Replace('BORDER_SHUFFLE','COLOR_SCALE').Replace('TERRITORY_GRAB','COLOR_CLAMP').Replace('PEACE_REJECTED','COLOR_INT_RED').Replace('MAP_REDRAWN','COLOR_INT_GREEN').Replace('DEAL_BROKEN','COLOR_INT_BLUE').Replace('COLONY_PLANTED','COLOR_CLAMP_MID').Replace('RIGHTS_REVOKED','COLOR_SCALE_ZERO').Replace('WATER_STOLEN','COLOR_INT_ORANGE')


	# 17-24
    $c=$c.Replace('FREE_PALESTINE','RAY_BASIC').Replace('APARTHEID_STATE','RAY_ARBITRARY').Replace('NAKBA_REMEMBER','RAY_NEGATIVE').Replace('CEASEFIRE_NOW','RAY_RANDOM').Replace('OCCUPATION_OVER','RAY_X_AXIS').Replace('BOYCOTT_ISRAEL','RAY_Y_AXIS').Replace('SETTLER_VIOLENCE','RAY_FRACTIONAL').Replace('RESISTANCE_FIRST','RAY_LARGE_ORIGIN').Replace('CHECKPOINT_HELL','RAY_ZEROS')
    $c=$c.Replace('VETO_AGAIN','RAYAT_POSITIVE').Replace('WAR_CRIME_REPEAT','RAYAT_ZERO').Replace('UN_IGNORED_AGAIN','RAYAT_NEGATIVE').Replace('VIOLATION_LOOP','RAYAT_ARBITRARY').Replace('EXCUSE_RECYCLED','RAYAT_ORIGIN').Replace('BOMBING_REPEAT','RAYAT_DIAG').Replace('DENIAL_AGAIN','RAYAT_FRACTION').Replace('HASBARA_REPLAY','RAYAT_RANDOM').Replace('BLOCKADE_ONGOING','RAYAT_Z_AXIS').Replace('PROPAGANDA_LOOP','RAYAT_Y_AXIS')
    $c=$c.Replace('IRON_DOME_MISS','HIT_DEAD_CENTER').Replace('MOSSAD_TYPO','HIT_MISS_FAR').Replace('BIBI_STUTTER','HIT_TANGENT').Replace('TSAHAL_MISFIRE','HIT_BEHIND_CAM').Replace('HASBARA_STATIC','HIT_LARGE_RADIUS').Replace('MERKAVA_STALL','HIT_INSIDE_SPHERE').Replace('SHEKEL_DROPPED','HIT_OFF_AXIS').Replace('SIGNAL_JAMMED','HIT_ORIGIN_SPHERE').Replace('EILAT_OFFLINE','HIT_GROUND_PLANE').Replace('NEGEV_DRY','HIT_CLOSE_MISS')
    $c=$c.Replace('BIBI_INDICTED','SKY_UP').Replace('LIKUD_CRUMBLES','SKY_DOWN').Replace('COALITION_SPLIT','SKY_HORIZ').Replace('KNESSET_CIRCUS','SKY_DIAG_UP').Replace('CORRUPTION_PRIME','SKY_FORWARD').Replace('BRIBERY_FACTOR','SKY_MOSTLY_UP').Replace('FRAUD_EXPOSED','SKY_MOSTLY_DOWN').Replace('SCANDAL_UNFOLDS','SKY_FAR_ORIGIN').Replace('ELECTION_FARCE','SKY_SIDE_UP').Replace('REGIME_COLLAPSE','SKY_SLIGHT_DOWN')
    $c=$c.Replace('HISTORY_REWRITE','NORM_TOP').Replace('NARRATIVE_FLIP','NORM_RIGHT').Replace('TRUTH_INVERTED','NORM_FRONT').Replace('FACTS_REVERSED','NORM_BOTTOM').Replace('TIMELINE_FAKE','NORM_CLAMP_CHECK').Replace('MAP_DISTORTED','NORM_CENTER').Replace('VICTIM_CARD','NORM_LEFT').Replace('STORY_TWISTED','NORM_DIAG')
    $c=$c.Replace('CASUALTIES_HIDDEN','DIFF_DIRECT').Replace('AID_BLOCKED','DIFF_PERP').Replace('BUDGET_MILITARY','DIFF_OPPOSITE').Replace('SUBSIDY_US','DIFF_45DEG').Replace('BILLION_WASTED','DIFF_BLUE').Replace('FUNDING_WEAPONS','DIFF_GREEN').Replace('DEFICIT_MORAL','DIFF_HALF').Replace('DEATH_TOLL_REAL','DIFF_NONUNIT_LDIR').Replace('COST_OF_WAR','DIFF_GRAZING')
    $c=$c.Replace('NATION_DIVIDED','SHADOW_NONE').Replace('TERRITORY_CARVED','SHADOW_BLOCKED').Replace('MANDATE_BROKEN','SHADOW_CLOSE_LIGHT').Replace('PARTITION_FORCED','SHADOW_LIGHT_BEHIND').Replace('LAND_GRABBED','SHADOW_NEAR_MISS').Replace('FAMILY_SEPARATED','SHADOW_DIRECT_BLOCK').Replace('RESOURCE_STOLEN','SHADOW_GROUND').Replace('WATER_CUT_OFF','SHADOW_ZERO_DIST').Replace('PEOPLE_DISPLACED','SHADOW_FAR_AWAY').Replace('BORDER_CARVED','SHADOW_PASS')
    $c=$c.Replace('BIBI_INDICTED','RT_HEADER_P3').Replace('LIKUD_CRUMBLES','RT_DIMENSIONS').Replace('COALITION_SPLIT','RT_MAX_COLOR').Replace('KNESSET_CIRCUS','RT_PIXEL_COUNT').Replace('CORRUPTION_PRIME','RT_SKY_COLOR').Replace('BRIBERY_FACTOR','RT_SPHERE_EXISTS').Replace('FRAUD_EXPOSED','RT_SHADOWS_EXIST').Replace('SCANDAL_UNFOLDS','RT_GROUND_EXISTS').Replace('ELECTION_FARCE','RT_RGB_RANGE').Replace('REGIME_COLLAPSE','RT_DONE')

    [IO.File]::WriteAllText($_.FullName, $c)
}

Write-Host "Done"
